version: '3.8'
name: 'digital-wallet'
services:
  postgres:
    image: postgres:14.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=dw_role
      - POSTGRES_PASSWORD=5tBsPvvXUBDw25zt
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_MULTIPLE_DATABASES=users,transactions
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_init/:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $DATABASE__USER']
      interval: 5s
      timeout: 5s
      retries: 5
  nats:
    image: nats:2.10.12-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    user: root
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS="user-created-topic:10:3;acknowledge-user-created-topic:10:3"
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      zookeeper:
        condition: service_started
volumes:
    pgdata:
    kafka-data:
